### ISSUE TITLE
Making mail sending work within Docker container

### ISSUE THREAD

**Issue by Julianoe** [evertramos/wordpress-docker-letsencrypt#10]
I've seen a multitude of posts ([issues from docker-library/wordpress ](https://github.com/docker-library/wordpress/issues/30), or [from docker-lirbary/php](https://github.com/docker-library/php/issues/135)) that discuss in thousands of messages this issue.

How do you make your server able to send mails? Do you have an easy way to do it? (that i could add to my tutorial-guide)

As i mentioned in another issue for now when i ask for a password recovery for example wordpress tells that mail() may not be activated in the server.

**Comment by evertramos** [comment]
Dude,

This is not an issue in my compose file... you must update your wordpress container with whatever you need to send e-mails....

I do use it but yes, it does not work sending e-mails...

I will fix later on, but no time right now... sorry.

When I fix, I will post it here.
